name: motoca

services:
  db:
    container_name: 'db'
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motoca
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  broker:
    container_name: broker
    image: rabbitmq:4.0.2-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  api:
    image: ${DOCKER_REGISTRY-}motoca-api
    build:
      context: .
      dockerfile: src/Motoca.API/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
