#version: '3.8'
name: motoca

services:
  db:
    container_name: 'db'
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motoca
    ports:
      - 5432:5432
  
  broker:
    container_name: broker
    image: rabbitmq:4.0.2-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  Motoca.Consumer:
    image: ${DOCKER_REGISTRY-}motocaconsumer
    build:
      context: .
      dockerfile: src/Motoca.Consumer/Dockerfile
    depends_on:
      - broker